"""Browser configuration - Chrome launch args, profile settings, and browser profile.

Abstracted from browser_use's browser/profile.py - keeps only the configuration layer,
dropping cloud browser, extensions, HAR recording, and other non-core features.
"""

import os
import sys
import tempfile
from collections.abc import Iterable
from enum import Enum
from functools import cache
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlparse

from pydantic import AfterValidator, BaseModel, ConfigDict, Field, field_validator
from typing_extensions import Annotated

# ============================================================================
# Constants
# ============================================================================

CHROME_DEBUG_PORT = 9242  # non-default port to avoid conflicts

CHROME_DISABLED_COMPONENTS = [
    'AcceptCHFrame',
    'AutoExpandDetailsElement',
    'AvoidUnnecessaryBeforeUnloadCheckSync',
    'CertificateTransparencyComponentUpdater',
    'DestroyProfileOnBrowserClose',
    'DialMediaRouteProvider',
    'ExtensionManifestV2Disabled',
    'GlobalMediaControls',
    'HttpsUpgrades',
    'ImprovedCookieControls',
    'LazyFrameLoading',
    'LensOverlay',
    'MediaRouter',
    'PaintHolding',
    'ThirdPartyStoragePartitioning',
    'Translate',
    'AutomationControlled',
    'BackForwardCache',
    'OptimizationHints',
    'ProcessPerSiteUpToMainFrameThreshold',
    'InterestFeedContentSuggestions',
    'CalculateNativeWinOcclusion',
    'HeavyAdPrivacyMitigations',
    'PrivacySandboxSettings4',
    'AutofillServerCommunication',
    'CrashReporting',
    'OverscrollHistoryNavigation',
    'InfiniteSessionRestore',
    'ExtensionDisableUnsupportedDeveloper',
    'ExtensionManifestV2Unsupported',
]

CHROME_HEADLESS_ARGS = ['--headless=new']

CHROME_DOCKER_ARGS = [
    '--no-sandbox',
    '--disable-gpu-sandbox',
    '--disable-setuid-sandbox',
    '--disable-dev-shm-usage',
    '--no-xshm',
    '--no-zygote',
    '--disable-site-isolation-trials',
]

CHROME_DISABLE_SECURITY_ARGS = [
    '--disable-site-isolation-trials',
    '--disable-web-security',
    '--disable-features=IsolateOrigins,site-per-process',
    '--allow-running-insecure-content',
    '--ignore-certificate-errors',
    '--ignore-ssl-errors',
    '--ignore-certificate-errors-spki-list',
]

CHROME_DETERMINISTIC_RENDERING_ARGS = [
    '--deterministic-mode',
    '--js-flags=--random-seed=1157259159',
    '--force-device-scale-factor=2',
    '--enable-webgl',
    '--font-render-hinting=none',
    '--force-color-profile=srgb',
]

CHROME_PERFORMANCE_ARGS = [
    # Minimal flags for best performance — restores Chrome's native optimizations:
    # DNS prefetch, QUIC/HTTP3, bfcache, TLS session resumption, SW cache, etc.
    '--no-first-run',
    '--no-default-browser-check',
    '--disable-default-apps',
    '--disable-sync',
    '--disable-breakpad',
    '--disable-blink-features=AutomationControlled',
    '--disable-features=Translate',
]

CHROME_DEFAULT_ARGS = [
    # Full automation flags — disables many Chrome optimizations for deterministic behavior.
    # Use performance_mode=True to skip these and get near-native speed.
    '--disable-field-trial-config',
    '--disable-background-networking',
    '--disable-background-timer-throttling',
    '--disable-backgrounding-occluded-windows',
    '--disable-back-forward-cache',
    '--disable-breakpad',
    '--disable-client-side-phishing-detection',
    '--disable-component-extensions-with-background-pages',
    '--disable-component-update',
    '--no-default-browser-check',
    '--disable-dev-shm-usage',
    '--disable-hang-monitor',
    '--disable-ipc-flooding-protection',
    '--disable-popup-blocking',
    '--disable-prompt-on-repost',
    '--disable-renderer-backgrounding',
    '--metrics-recording-only',
    '--no-first-run',
    '--no-service-autorun',
    '--export-tagged-pdf',
    '--disable-search-engine-choice-screen',
    '--unsafely-disable-devtools-self-xss-warnings',
    '--enable-features=NetworkService,NetworkServiceInProcess',
    '--enable-network-information-downlink-max',
    '--test-type=gpu',
    '--disable-sync',
    '--allow-legacy-extension-manifests',
    '--allow-pre-commit-input',
    '--disable-blink-features=AutomationControlled',
    '--install-autogenerated-theme=0,0,0',
    '--log-level=2',
    '--disable-focus-on-load',
    '--disable-window-activation',
    '--generate-pdf-document-outline',
    '--no-pings',
    '--ash-no-nudges',
    '--disable-infobars',
    '--simulate-outdated-no-au="Tue, 31 Dec 2099 23:59:59 GMT"',
    '--hide-crash-restore-bubble',
    '--suppress-message-center-popups',
    '--disable-domain-reliability',
    '--disable-datasaver-prompt',
    '--disable-speech-synthesis-api',
    '--disable-speech-api',
    '--disable-print-preview',
    '--safebrowsing-disable-auto-update',
    '--disable-external-intent-requests',
    '--disable-desktop-notifications',
    '--noerrdialogs',
    '--silent-debugger-extension-api',
    '--disable-extensions-http-throttling',
    '--extensions-on-chrome-urls',
    '--disable-default-apps',
    f'--disable-features={",".join(CHROME_DISABLED_COMPONENTS)}',
]


# ============================================================================
# Helper functions
# ============================================================================


@cache
def is_running_in_docker() -> bool:
    """Detect if running in a Docker container."""
    try:
        if Path('/.dockerenv').exists() or 'docker' in Path('/proc/1/cgroup').read_text().lower():
            return True
    except Exception:
        pass
    return False


def _find_free_port() -> int:
    """Find a free TCP port."""
    import socket

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        return s.getsockname()[1]


def validate_url(url: str, schemes: Iterable[str] = ()) -> str:
    """Validate URL format."""
    parsed_url = urlparse(url)
    if not parsed_url.netloc:
        raise ValueError(f'Invalid URL format: {url}')
    if schemes and parsed_url.scheme and parsed_url.scheme.lower() not in schemes:
        raise ValueError(f'URL has invalid scheme: {url} (expected one of {schemes})')
    return url


def validate_cli_arg(arg: str) -> str:
    """Validate that arg is a valid CLI argument."""
    if not arg.startswith('--'):
        raise ValueError(f'Invalid CLI argument: {arg} (should start with --)')
    return arg


UrlStr = Annotated[str, AfterValidator(validate_url)]
CliArgStr = Annotated[str, AfterValidator(validate_cli_arg)]


# ============================================================================
# Models
# ============================================================================


class ViewportSize(BaseModel):
    """Viewport dimensions."""

    width: int = Field(ge=0)
    height: int = Field(ge=0)


class ProxySettings(BaseModel):
    """Proxy configuration."""

    server: str | None = None
    bypass: str | None = None
    username: str | None = None
    password: str | None = None


class BrowserChannel(str, Enum):
    """Supported browser channels."""

    CHROMIUM = 'chromium'
    CHROME = 'chrome'
    CHROME_BETA = 'chrome-beta'
    CHROME_DEV = 'chrome-dev'
    CHROME_CANARY = 'chrome-canary'
    MSEDGE = 'msedge'


class BrowserConfig(BaseModel):
    """Configuration for launching/connecting to a Chromium-based browser.

    This is a simplified version of browser_use's BrowserProfile, keeping only
    the core browser launching and connection configuration.

    Usage:
        # Local browser
        config = BrowserConfig(headless=False)
        session = BrowserSession(config=config)
        await session.start()

        # Connect to existing browser
        config = BrowserConfig(cdp_url="http://localhost:9222")
        session = BrowserSession(config=config)
        await session.start()
    """

    model_config = ConfigDict(
        extra='ignore',
        validate_assignment=True,
        revalidate_instances='always',
        populate_by_name=True,
    )

    # === Connection mode ===
    cdp_url: str | None = Field(default=None, description='CDP URL to connect to an already-running browser')
    is_local: bool = Field(default=False, description='Whether to launch a local browser (auto-set if no cdp_url)')

    # === Browser executable ===
    executable_path: str | Path | None = Field(
        default=None, description='Path to the Chromium-based browser executable'
    )
    channel: BrowserChannel | None = Field(
        default=None, description='Browser channel (auto-discovers the executable)'
    )

    # === Browser profile ===
    user_data_dir: str | Path | None = Field(
        default=None, description='Path to the user data directory (persistent profile)'
    )
    profile_directory: str = Field(
        default='Default', description='Profile subdirectory name inside user_data_dir'
    )

    # === Display ===
    headless: bool = Field(default=True, description='Run browser in headless mode')
    window_size: dict[str, int] | None = Field(
        default=None, description='Window size, e.g. {"width": 1280, "height": 720}'
    )
    window_position: dict[str, int] | None = Field(
        default=None, description='Window position, e.g. {"width": 0, "height": 0}'
    )
    viewport: ViewportSize | None = Field(
        default=None, description='Override viewport size (None = use window size)'
    )
    device_scale_factor: float | None = Field(default=None, description='Device scale factor (1.0, 2.0, etc.)')
    no_viewport: bool = Field(default=False, description="Don't set an explicit viewport")

    # === Networking ===
    user_agent: str | None = Field(default=None, description='Custom User-Agent string')
    proxy: ProxySettings | None = Field(default=None, description='Proxy configuration')
    headers: dict[str, str] | None = Field(
        default=None, description='Extra HTTP headers for CDP connection'
    )

    # === Security ===
    disable_security: bool = Field(
        default=False, description='Disable web security features (CORS, etc.)'
    )
    chromium_sandbox: bool = Field(
        default=True, description='Enable Chromium sandbox (disable for Docker)'
    )

    # === Rendering ===
    deterministic_rendering: bool = Field(
        default=False, description='Enable deterministic rendering for consistent screenshots'
    )

    # === Extensions ===
    enable_default_extensions: bool = Field(
        default=True, description='Load default browser extensions (ad blocker, cookie handler)'
    )

    # === Extra ===
    args: list[str] = Field(default_factory=list, description='Extra CLI args to pass to Chrome')
    ignore_default_args: list[str] | Literal[True] = Field(
        default_factory=list,
        description='Default args to exclude (or True to exclude ALL defaults)',
    )
    env: dict[str, str | float | bool] | None = Field(
        default=None, description='Extra environment variables for the browser process'
    )

    # === File download ===
    downloads_path: str | Path | None = Field(
        default=None, description='Directory for downloaded files'
    )
    accept_downloads: bool = Field(default=True, description='Accept file downloads')

    # === Other ===
    keep_alive: bool = Field(
        default=False, description='Keep browser alive after session ends'
    )
    performance_mode: bool = Field(
        default=True,
        description='Use minimal Chrome flags for near-native speed (DNS prefetch, QUIC, bfcache, etc.)',
    )
    permissions: list[str] = Field(
        default_factory=lambda: ['clipboardReadWrite', 'notifications'],
        description='Browser permissions to grant',
    )
    allowed_domains: list[str] | None = Field(
        default=None, description='Restrict navigation to these domains'
    )
    prohibited_domains: list[str] | None = Field(
        default=None, description='Block navigation to these domains'
    )

    # === Timing ===
    minimum_wait_page_load_time: float = Field(
        default=0.5, description='Minimum time to wait after page load (seconds)'
    )
    wait_for_network_idle_page_load_time: float = Field(
        default=0.5, description='Time to wait for network idle after page load'
    )
    wait_between_actions: float = Field(
        default=0.5, description='Wait time between actions (seconds)'
    )

    @field_validator('user_data_dir', mode='before')
    @classmethod
    def resolve_user_data_dir(cls, v: str | Path | None) -> str | None:
        if v is None:
            return None
        return str(Path(v).expanduser().resolve())

    def get_args(self) -> list[str]:
        """Build the complete list of Chrome CLI launch arguments."""

        if self.user_data_dir is None:
            if self.performance_mode:
                # Persistent profile for cache/cookies/DNS/TLS session reuse
                self.user_data_dir = str(Path.home() / '.taus-browser-profile')
            else:
                # Create a temp directory for isolation
                self.user_data_dir = tempfile.mkdtemp(prefix='taus-browser-')

        base_args = CHROME_PERFORMANCE_ARGS if self.performance_mode else CHROME_DEFAULT_ARGS

        if isinstance(self.ignore_default_args, list):
            default_args = [a for a in base_args if a not in self.ignore_default_args]
        elif self.ignore_default_args is True:
            default_args = []
        else:
            default_args = list(base_args)

        # Collect all args
        pre_args = [
            *default_args,
            *self.args,
            f'--user-data-dir={self.user_data_dir}',
            f'--profile-directory={self.profile_directory}',
            *(CHROME_DOCKER_ARGS if (is_running_in_docker() or not self.chromium_sandbox) else []),
            *(CHROME_HEADLESS_ARGS if self.headless else []),
            *(CHROME_DISABLE_SECURITY_ARGS if self.disable_security else []),
            *(CHROME_DETERMINISTIC_RENDERING_ARGS if self.deterministic_rendering else []),
            *(
                [f'--window-size={self.window_size["width"]},{self.window_size["height"]}']
                if self.window_size
                else (['--start-maximized'] if not self.headless else [])
            ),
            *(
                [f'--window-position={self.window_position["width"]},{self.window_position["height"]}']
                if self.window_position
                else []
            ),
        ]

        # Proxy
        if self.proxy and self.proxy.server:
            pre_args.append(f'--proxy-server={self.proxy.server}')
            if self.proxy.bypass:
                pre_args.append(f'--proxy-bypass-list={self.proxy.bypass}')

        # User agent
        if self.user_agent:
            pre_args.append(f'--user-agent={self.user_agent}')

        # Merge --disable-features values
        disable_features_values: list[str] = []
        non_disable_features_args: list[str] = []

        for arg in pre_args:
            if arg.startswith('--disable-features='):
                features = arg.split('=', 1)[1]
                disable_features_values.extend(features.split(','))
            else:
                non_disable_features_args.append(arg)

        if disable_features_values:
            unique_features = list(dict.fromkeys(f.strip() for f in disable_features_values if f.strip()))
            non_disable_features_args.append(f'--disable-features={",".join(unique_features)}')

        # Deduplicate args (last wins for duplicate keys)
        seen_keys: dict[str, str] = {}
        for arg in non_disable_features_args:
            if '=' in arg:
                key = arg.split('=', 1)[0]
                seen_keys[key] = arg
            else:
                seen_keys[arg] = arg

        return list(seen_keys.values())


# ============================================================================
# Chrome executable discovery
# ============================================================================


def find_chrome_executable() -> str | None:
    """Find an installed Chrome/Chromium browser executable."""

    # Check env var first
    env_path = os.environ.get('CHROME_PATH') or os.environ.get('BROWSER_PATH')
    if env_path and Path(env_path).exists():
        return env_path

    if sys.platform == 'darwin':
        candidates = [
            '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            '/Applications/Chromium.app/Contents/MacOS/Chromium',
            '/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge',
            '/Applications/Brave Browser.app/Contents/MacOS/Brave Browser',
        ]
    elif sys.platform == 'linux':
        candidates = [
            'google-chrome',
            'google-chrome-stable',
            'chromium',
            'chromium-browser',
            'microsoft-edge',
            '/usr/bin/google-chrome',
            '/usr/bin/chromium',
            '/usr/bin/chromium-browser',
            '/snap/bin/chromium',
        ]
    elif sys.platform == 'win32':
        candidates = [
            'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
            'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
            'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe',
            os.path.expandvars('%LocalAppData%\\Google\\Chrome\\Application\\chrome.exe'),
        ]
    else:
        candidates = []

    for path in candidates:
        if Path(path).exists():
            return path

    # Try shutil.which
    import shutil

    for name in ['google-chrome', 'chromium', 'chromium-browser', 'google-chrome-stable']:
        found = shutil.which(name)
        if found:
            return found

    return None
